# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_aggregate_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etenseal_aggregate_server.proto\"G\n\rbottom_output\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x12\n\nparams_msg\x18\x03 \x01(\x0c\"4\n\x0b\x62ottom_grad\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x10\n\x08grad_msg\x18\x02 \x01(\x0c\x32H\n\x16\x41ggregateServerService\x12.\n\x0emiddle_forward\x12\x0e.bottom_output\x1a\x0c.bottom_gradb\x06proto3')



_BOTTOM_OUTPUT = DESCRIPTOR.message_types_by_name['bottom_output']
_BOTTOM_GRAD = DESCRIPTOR.message_types_by_name['bottom_grad']
bottom_output = _reflection.GeneratedProtocolMessageType('bottom_output', (_message.Message,), {
  'DESCRIPTOR' : _BOTTOM_OUTPUT,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:bottom_output)
  })
_sym_db.RegisterMessage(bottom_output)

bottom_grad = _reflection.GeneratedProtocolMessageType('bottom_grad', (_message.Message,), {
  'DESCRIPTOR' : _BOTTOM_GRAD,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:bottom_grad)
  })
_sym_db.RegisterMessage(bottom_grad)

_AGGREGATESERVERSERVICE = DESCRIPTOR.services_by_name['AggregateServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTTOM_OUTPUT._serialized_start=34
  _BOTTOM_OUTPUT._serialized_end=105
  _BOTTOM_GRAD._serialized_start=107
  _BOTTOM_GRAD._serialized_end=159
  _AGGREGATESERVERSERVICE._serialized_start=161
  _AGGREGATESERVERSERVICE._serialized_end=233
# @@protoc_insertion_point(module_scope)
