# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tenseal_aggregate_server_pb2 as tenseal__aggregate__server__pb2


class AggregateServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.middle_forward = channel.unary_unary(
                '/AggregateServerService/middle_forward',
                request_serializer=tenseal__aggregate__server__pb2.bottom_output.SerializeToString,
                response_deserializer=tenseal__aggregate__server__pb2.bottom_grad.FromString,
                )


class AggregateServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def middle_forward(self, request, context):
        """AggregateServer provides the interface, client remotes the call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregateServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'middle_forward': grpc.unary_unary_rpc_method_handler(
                    servicer.middle_forward,
                    request_deserializer=tenseal__aggregate__server__pb2.bottom_output.FromString,
                    response_serializer=tenseal__aggregate__server__pb2.bottom_grad.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AggregateServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AggregateServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def middle_forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregateServerService/middle_forward',
            tenseal__aggregate__server__pb2.bottom_output.SerializeToString,
            tenseal__aggregate__server__pb2.bottom_grad.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
